# Generated by Django 6.0.2 on 2026-02-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-order', 'created_at']},
        ),
        migrations.AddField(
            model_name='contact',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
