# Generated by Django 6.0.2 on 2026-02-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0002_alter_notification_options_alter_todo_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='active',
            new_name='is_active',
        ),
    ]
