# Generated by Django 6.0.2 on 2026-03-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0006_answer_is_correct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['?']},
        ),
    ]
